### ISSUE TITLE
[Bug]: 安装此插件之后漏斗无法正常吸物品

### ISSUE THREAD

**Issue by BensonChen2456** [SurvivalApparatusCommunication/BedrockBugFixes#5]
### Describe the bug

安装此插件之后漏斗无法正常吸物品

### To Reproduce

安装此插件之后漏斗无法正常吸物品

### Expected behavior

安装此插件之后漏斗无法正常吸物品

### Platform

Windows Sever 2016

### BDS Version

1.21.3

### LeviLamina Version

0.13.5

### Version

Latest

**Comment by OEOTYAN** [comment]
https://github.com/SurvivalApparatusCommunication/BedrockBugFixes/actions/runs/10548395358/artifacts/1852071313 ll的bug，修好了，用这个action的
