### ISSUE TITLE
[Bug]: 0.1.5版本漏斗无法正常使用

### ISSUE THREAD

**Issue by lc655254** [SurvivalApparatusCommunication/BedrockBugFixes#6]
### Describe the bug

因0.1.6版本安装后无法正常使用(LL均为最新版本) 看到群里您说安装0.1.5版本的  于是我就使用了0.1.5此版本
但安装之后就无法正常使用漏斗了  漏斗能正常漏下去 但无法正常吸进去

### To Reproduce

安装插件后 正常使用就无法正常吸入

### Expected behavior

我使用了/bbfconfig bugfix hopper_bugs_fix false之后就可以正常使用了

### Screenshots

![image](https://github.com/user-attachments/assets/6392eac5-994e-4ffc-899f-f8ceadf8d39b)
![image](https://github.com/user-attachments/assets/374c53df-8908-4556-ae72-2aa8ec354445)
这是/bbfconfig bugfix hopper_bugs_fix true之后的
false之后可以正常使用

### Platform

windows 10

### BDS Version

1.21.x

### LeviLamina Version

0.13.5

### Version

0.1.5

**Comment by ShrBox** [comment]
建议先关闭这个功能，因为BlockSource虚表坏了
