### ISSUE TITLE
[Bug]: 插件无法加载

### ISSUE THREAD

**Issue by Atrium4641** [SurvivalApparatusCommunication/BedrockBugFixes#7]
### Describe the bug

![image](https://github.com/user-attachments/assets/af87f7c1-7e65-4aac-beac-01e23cbfeb72)

### To Reproduce

1

### Expected behavior

正常加载

### Screenshots

![image](https://github.com/user-attachments/assets/af87f7c1-7e65-4aac-beac-01e23cbfeb72)

### Platform

Win10

### BDS Version

1.21.3

### LeviLamina Version

0.13.5

### Version

0.1.6

### Additional context

1

**Comment by OEOTYAN** [comment]
用0.1.5
